USE rexchula;

DROP TABLE IF EXISTS `subject`;

CREATE TABLE `subject`
(
	SubjectID CHAR(7) PRIMARY KEY,
    NameAbv VARCHAR(128) UNIQUE NOT NULL,
    NameEN VARCHAR(128) UNIQUE,
    NameTH VARCHAR(128) UNIQUE,
    Credit INT UNSIGNED NOT NULL
);