USE rexchula;

DROP TABLE IF EXISTS `subject`;

CREATE TABLE `subject`
(
	SubjectID CHAR(7) PRIMARY KEY,
    NameAbv VARCHAR(128) NOT NULL,
    NameEN VARCHAR(128),
    NameTH VARCHAR(128),
    Credit INT UNSIGNED NOT NULL
);